name: AQAL-Test
favicon: null
layout_spectrum: 0.2414136310108006
typography_spectrum: 0.28016705997288227
title: AQAL Test
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c30d5b'
    - '#45484e'
    - '#ffffff'
    - '#000000'
    - '#f2cddd'
  brandStrength: 0.552072853082791
  lightness: 0.9251016387715936
  saturation: 0.4076235890388489
  rhythmicContrast: 0.7583360418211669
purpose: []
